//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstoolTechRestFullAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class orderapiEntities1 : DbContext
    {
        public orderapiEntities1()
            : base("name=orderapiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientMaster__Rf> ClientMaster__Rf { get; set; }
        public virtual DbSet<prodactacoun> prodactacoun { get; set; }
        public virtual DbSet<RefreshTokenRf> RefreshTokenRf { get; set; }
        public virtual DbSet<UserMaster> UserMaster { get; set; }
    }
}
