//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstoolTechRestFullAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodactacoun
    {
        public int ID { get; set; }
        public string namear { get; set; }
        public string nameen { get; set; }
        public Nullable<int> groupID { get; set; }
        public string barcode { get; set; }
        public Nullable<bool> rabtwithmored { get; set; }
        public Nullable<int> IDformred { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<bool> dateexpire { get; set; }
        public Nullable<bool> cashonly { get; set; }
        public Nullable<bool> notback { get; set; }
        public Nullable<bool> backamount { get; set; }
        public Nullable<int> backday { get; set; }
        public string manfacture { get; set; }
        public Nullable<double> hightt { get; set; }
        public Nullable<double> wedthh { get; set; }
        public Nullable<double> ertfah { get; set; }
        public Nullable<double> wazen { get; set; }
        public Nullable<int> reoreder { get; set; }
        public string detalis { get; set; }
        public Nullable<bool> multiparcod { get; set; }
        public Nullable<bool> notifiexpiredateday { get; set; }
        public Nullable<bool> notifiexpiredate { get; set; }
        public Nullable<bool> notexitinstock { get; set; }
    }
}
