//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstoolTechRestFullAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshTokenRf
    {
        public string ID { get; set; }
        public string UserName { get; set; }
        public string ClientID { get; set; }
        public Nullable<System.DateTime> IssuedTime { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public string ProtectedTicket { get; set; }
    }
}
